services:
  traefik:
    image: traefik:v3.1.5
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mydashboard.rule=Host(`traefik.solmarket.info`)"
      - "traefik.http.routers.mydashboard.service=api@internal"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/certs/:/var/traefik/certs/:rw
    networks:
      - teaser-site
    restart: unless-stopped
    security_opt:
      - no-new-privilages:true
networks:
  teaser-site:
    external: true
