// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Predictionmarket struct {
	Marketid    int32
	Title       pgtype.Text
	Volume      int32
	Enddate     pgtype.Date
	Description string
}

type Predictionoption struct {
	Optionid    int32
	Marketid    int32
	Optiontext  string
	Optioncount int32
}
